package cc.dfsoft.project.biz.base.constructmanage.entity;

import java.io.Serializable;
import java.sql.Clob;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.sql.rowset.serial.SerialException;

import cc.dfsoft.project.biz.base.constructmanage.enums.RnStatusEnum;
import cc.dfsoft.project.biz.base.project.entity.Signature;
import cc.dfsoft.uexpress.common.util.ClobUtil;

/**
 * Model class of rectify_notice.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="RECTIFY_NOTICE")
public class RectifyNotice implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 384298263956674037L;
	/** serialVersionUID. */
	private String rnId;				//整改通知ID
	private String rnNo;				//整改通知编号
	private Date rnDate;				//整改通知日期
	private String projId;				//工程ID
	private String projNo;				//工程编号
	private String projName;			//工程名称
	private String projAddr;			//工程地点
	private String corpId;				//分公司ID
	private String tenantId;			//租户ID
	private String orgId;				//权限ID
	private String deptId;				//部门ID
	private String constructionUnit;	//施工单位
	private Clob builder;				//施工员签字
	private Clob qsGroup;				//市场发展部质量安全组签字
	private Clob tdCompany;				//输配公司签字
	private Clob custService;			//客户服务中心签字
	private Clob networkCenter;			//管网数据中心签字
	private Clob fieldRepresent;		//现场代表
	private String fieldRepresentName;	//现场代表ID
	private Clob designer;				//设计人员签字
	private String suName;				//监理单位
	private Clob suJgj;					//监理签字
	private String corpName;			//分公司名称
	private String rnCreateStaffId;		//通知创建人ID
	private String rnCreateStaff;		//通知创建人
	private Date rnCreateTime;			//通知创建时间
	private String limitTime;			//整改期限
	private String rnQuestions;			//存在问题
	private Clob metrologyOffice;		//计量所
	private Clob cuPLeader;				//施工单位签字
	private List<Signature> sign;		//签字
	private String rnStatus;			//整改通知状态
	private String rnStatusDes;			//整改通知状态----列表显示
	private String busOrderId;			//验收单ID
	
	private String rnExplain;			//整改说明
	private String selfCheckResult;		//自检结果
	private String reinspectionResult;	//复验结果
	private Clob cuPleaderBack;			//施工单位回复签字
	private Clob suJgjBack;				//监理单位确认签字
	private Date selfCheckDate;			//自检日期
	private Date reinspectionDate;		//复验日期
	private Integer version;				//版本控制
	
	private String rectifyNoticeType;	//验收单类型

	private String review;	//复查情况

	/**
	 * Constructor.
	 */
	public RectifyNotice() {
	}

	/**
	 * Set the 整改通知ID.
	 * 
	 * @param rnId
	 *            整改通知ID
	 */
	public void setRnId(String rnId) {
		this.rnId = rnId;
	}

	/**
	 * Get the 整改通知ID.
	 * 
	 * @return 整改通知ID
	 */
	@Id
	@Column(name="RN_ID",unique = true)
	public String getRnId() {
		return this.rnId;
	}

	/**
	 * Set the 整改通知编号.
	 * 
	 * @param rnNo
	 *            整改通知编号
	 */
	public void setRnNo(String rnNo) {
		this.rnNo = rnNo;
	}

	/**
	 * Get the 整改通知编号.
	 * 
	 * @return 整改通知编号
	 */
	@Column(name="RN_NO")
	public String getRnNo() {
		return this.rnNo;
	}

	/**
	 * Set the 整改通知日期.
	 * 
	 * @param rnDate
	 *            整改通知日期
	 */
	public void setRnDate(Date rnDate) {
		this.rnDate = rnDate;
	}

	/**
	 * Get the 整改通知日期.
	 * 
	 * @return 整改通知日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name="RN_DATE")
	public Date getRnDate() {
		return this.rnDate;
	}

	/**
	 * Set the 工程ID.
	 * 
	 * @param projId
	 *            工程ID
	 */
	public void setProjId(String projId) {
		this.projId = projId;
	}

	/**
	 * Get the 工程ID.
	 * 
	 * @return 工程ID
	 */
	@Column(name="PROJ_ID")
	public String getProjId() {
		return this.projId;
	}

	/**
	 * Set the 工程编号.
	 * 
	 * @param projNo
	 *            工程编号
	 */
	public void setProjNo(String projNo) {
		this.projNo = projNo;
	}

	/**
	 * Get the 工程编号.
	 * 
	 * @return 工程编号
	 */
	@Column(name="PROJ_NO")
	public String getProjNo() {
		return this.projNo;
	}

	/**
	 * Set the 工程名称.
	 * 
	 * @param projName
	 *            工程名称
	 */
	public void setProjName(String projName) {
		this.projName = projName;
	}

	/**
	 * Get the 工程名称.
	 * 
	 * @return 工程名称
	 */
	@Column(name="PROJ_NAME")
	public String getProjName() {
		return this.projName;
	}

	/**
	 * Set the 工程地点.
	 * 
	 * @param projAddr
	 *            工程地点
	 */
	public void setProjAddr(String projAddr) {
		this.projAddr = projAddr;
	}

	/**
	 * Get the 工程地点.
	 * 
	 * @return 工程地点
	 */
	@Column(name="PROJ_ADDR")
	public String getProjAddr() {
		return this.projAddr;
	}

	/**
	 * Set the 分公司ID.
	 * 
	 * @param corpId
	 *            分公司ID
	 */
	public void setCorpId(String corpId) {
		this.corpId = corpId;
	}

	/**
	 * Get the 分公司ID.
	 * 
	 * @return 分公司ID
	 */
	@Column(name="CORP_ID")
	public String getCorpId() {
		return this.corpId;
	}

	/**
	 * Set the 租户ID.
	 * 
	 * @param tenantId
	 *            租户ID
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * Get the 租户ID.
	 * 
	 * @return 租户ID
	 */
	@Column(name="TENANT_ID")
	public String getTenantId() {
		return this.tenantId;
	}

	/**
	 * Set the 权限ID.
	 * 
	 * @param orgId
	 *            权限ID
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * Get the 权限ID.
	 * 
	 * @return 权限ID
	 */
	@Column(name="ORG_ID")
	public String getOrgId() {
		return this.orgId;
	}

	/**
	 * Set the 施工单位.
	 * 
	 * @param constructionUnit
	 *            施工单位
	 */
	public void setConstructionUnit(String constructionUnit) {
		this.constructionUnit = constructionUnit;
	}

	/**
	 * Get the 施工单位.
	 * 
	 * @return 施工单位
	 */
	@Column(name="CONSTRUCTION_UNIT")
	public String getConstructionUnit() {
		return this.constructionUnit;
	}

	/**
	 * Set the 施工员签字.
	 * 
	 * @param builder
	 *            施工员签字
	 */
	public void setBuilder(String builder)throws SerialException, SQLException {
		this.builder = ClobUtil.stringToClob(builder);
	}

	/**
	 * Get the 施工员签字.
	 * 
	 * @return 施工员签字
	 */
	@Column(name="BUILDER")
	public String getBuilder() {
		return ClobUtil.ClobToString(this.builder);
	}

	/**
	 * Set the 市场发展部质量安全组签字.
	 * 
	 * @param qsGroup
	 *            市场发展部质量安全组签字
	 */
	public void setQsGroup(String qsGroup)throws SerialException, SQLException  {
		this.qsGroup = ClobUtil.stringToClob(qsGroup);
	}

	/**
	 * Get the 市场发展部质量安全组签字.
	 * 
	 * @return 市场发展部质量安全组签字
	 */
	@Column(name="QS_GROUP")
	public String getQsGroup() {
		return ClobUtil.ClobToString(this.qsGroup);
	}

	/**
	 * Set the 输配公司签字.
	 * 
	 * @param tdCompany
	 *            输配公司签字
	 */
	public void setTdCompany(String tdCompany)throws SerialException, SQLException {
		this.tdCompany = ClobUtil.stringToClob(tdCompany);
	}

	/**
	 * Get the 输配公司签字.
	 * 
	 * @return 输配公司签字
	 */
	@Column(name="TD_COMPANY")
	public String getTdCompany() {
		return ClobUtil.ClobToString(tdCompany);
	}

	/**
	 * Set the 客户服务中心签字.
	 * 
	 * @param custService
	 *            客户服务中心签字
	 */
	public void setCustService(String custService)throws SerialException, SQLException {
		this.custService = ClobUtil.stringToClob(custService);
	}

	/**
	 * Get the 客户服务中心签字.
	 * 
	 * @return 客户服务中心签字
	 */
	@Column(name="CUST_SERVICE")
	public String getCustService() {
		return ClobUtil.ClobToString(custService);
	}

	/**
	 * Set the 管网数据中心签字.
	 * 
	 * @param networkCenter
	 *            管网数据中心签字
	 * @throws SQLException 
	 * @throws SerialException 
	 */
	public void setNetworkCenter(String networkCenter) throws SerialException, SQLException {
		this.networkCenter = ClobUtil.stringToClob(networkCenter);
	}

	/**
	 * Get the 管网数据中心签字.
	 * 
	 * @return 管网数据中心签字
	 */
	@Column(name="NETWORK_CENTER")
	public String getNetworkCenter() {
		return ClobUtil.ClobToString(networkCenter);
	}

	/**
	 * Set the 现场代表.
	 * 
	 * @param fieldRepresent
	 *            现场代表
	 * @throws SQLException 
	 * @throws SerialException 
	 */
	public void setFieldRepresent(String fieldRepresent) throws SerialException, SQLException {
		this.fieldRepresent = ClobUtil.stringToClob(fieldRepresent);
	}

	/**
	 * Get the 现场代表.
	 * 
	 * @return 现场代表
	 */
	@Column(name="FIELD_REPRESENT")
	public String getFieldRepresent() {
		return ClobUtil.ClobToString(fieldRepresent);
	}

	/**
	 * Set the 现场代表ID.
	 * 
	 * @param fieldRepresentName
	 *            现场代表ID
	 */
	public void setFieldRepresentName(String fieldRepresentName) {
		this.fieldRepresentName = fieldRepresentName;
	}

	/**
	 * Get the 现场代表ID.
	 * 
	 * @return 现场代表ID
	 */
	@Column(name="FIELD_REPRESENT_NAME")
	public String getFieldRepresentName() {
		return this.fieldRepresentName;
	}

	/**
	 * Set the 设计人员签字.
	 * 
	 * @param designer
	 *            设计人员签字
	 * @throws SQLException 
	 * @throws SerialException 
	 */
	public void setDesigner(String designer) throws SerialException, SQLException {
		this.designer = ClobUtil.stringToClob(designer);
	}

	/**
	 * Get the 设计人员签字.
	 * 
	 * @return 设计人员签字
	 */
	@Column(name="DESIGNER")
	public String getDesigner() {
		return ClobUtil.ClobToString(designer);
	}

	/**
	 * Set the 监理单位.
	 * 
	 * @param suName
	 *            监理单位
	 */
	public void setSuName(String suName) {
		this.suName = suName;
	}

	/**
	 * Get the 监理单位.
	 * 
	 * @return 监理单位
	 */
	@Column(name="SU_NAME")
	public String getSuName() {
		return this.suName;
	}

	/**
	 * Set the 监理签字.
	 * 
	 * @param suJgj
	 *            监理签字
	 * @throws SQLException 
	 * @throws SerialException 
	 */
	public void setSuJgj(String suJgj) throws SerialException, SQLException {
		this.suJgj = ClobUtil.stringToClob(suJgj);
	}

	/**
	 * Get the 监理签字.
	 * 
	 * @return 监理签字
	 */
	@Column(name="SU_JGJ")
	public String getSuJgj() {
		return ClobUtil.ClobToString(this.suJgj);
	}

	/**
	 * Set the 分公司名称.
	 * 
	 * @param corpName
	 *            分公司名称
	 */
	public void setCorpName(String corpName) {
		this.corpName = corpName;
	}

	/**
	 * Get the 分公司名称.
	 * 
	 * @return 分公司名称
	 */
	@Column(name="CORP_NAME")
	public String getCorpName() {
		return this.corpName;
	}

	/**
	 * Set the 通知创建人ID.
	 * 
	 * @param rnCreateStaffId
	 *            通知创建人ID
	 */
	public void setRnCreateStaffId(String rnCreateStaffId) {
		this.rnCreateStaffId = rnCreateStaffId;
	}

	/**
	 * Get the 通知创建人ID.
	 * 
	 * @return 通知创建人ID
	 */
	@Column(name="RN_CREATE_STAFF_ID")
	public String getRnCreateStaffId() {
		return this.rnCreateStaffId;
	}

	/**
	 * Set the 通知创建人.
	 * 
	 * @param rnCreateStaff
	 *            通知创建人
	 */
	public void setRnCreateStaff(String rnCreateStaff) {
		this.rnCreateStaff = rnCreateStaff;
	}

	/**
	 * Get the 通知创建人.
	 * 
	 * @return 通知创建人
	 */
	@Column(name="RN_CREATE_STAFF")
	public String getRnCreateStaff() {
		return this.rnCreateStaff;
	}

	/**
	 * Set the 通知创建时间.
	 * 
	 * @param rnCreateTime
	 *            通知创建时间
	 */
	public void setRnCreateTime(Date rnCreateTime) {
		this.rnCreateTime = rnCreateTime;
	}

	/**
	 * Get the 通知创建时间.
	 * 
	 * @return 通知创建时间
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="RN_CREATE_TIME")
	public Date getRnCreateTime() {
		return this.rnCreateTime;
	}

	/**
	 * Set the 整改期限.
	 * 
	 * @param limitTime
	 *            整改期限
	 */
	public void setLimitTime(String limitTime) {
		this.limitTime = limitTime;
	}

	/**
	 * Get the 整改期限.
	 * 
	 * @return 整改期限
	 */
	@Column(name="LIMIT_TIME")
	public String getLimitTime() {
		return this.limitTime;
	}

	/**
	 * Set the 存在问题.
	 * 
	 * @param rnQuestions
	 *            存在问题
	 */
	public void setRnQuestions(String rnQuestions) {
		this.rnQuestions = rnQuestions;
	}

	/**
	 * Get the 存在问题.
	 * 
	 * @return 存在问题
	 */
	@Column(name="RN_QUESTIONS")
	public String getRnQuestions() {
		return this.rnQuestions;
	}

	@Column(name="DEPT_ID")
	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name="METROLOGY_OFFICE")
	public String getMetrologyOffice() {
		return ClobUtil.ClobToString(this.metrologyOffice);
	}

	public void setMetrologyOffice(String metrologyOffice) throws SerialException, SQLException {
		this.metrologyOffice = ClobUtil.stringToClob(metrologyOffice);
	}
    
	@Column(name="CU_PLEADER")
	public String getCuPLeader() {
		return ClobUtil.ClobToString(this.cuPLeader);
	}

	public void setCuPLeader(String cuPLeader) throws SerialException, SQLException {
		this.cuPLeader = ClobUtil.stringToClob(cuPLeader);
	}

	@Transient
	public List<Signature> getSign() {
		return sign;
	}

	public void setSign(List<Signature> sign) {
		this.sign = sign;
	}

	@Column(name="RN_STATUS")
	public String getRnStatus() {
		return rnStatus;
	}

	public void setRnStatus(String rnStatus) {
		this.rnStatus = rnStatus;
	}

	@Transient
	public String getRnStatusDes() {
		for(RnStatusEnum e: RnStatusEnum.values()) {
	   		if(e.getValue().equals(this.rnStatus)) {
	   			return e.getMessage();
	   		}
	   	}
		return "";
	}

	public void setRnStatusDes(String rnStatusDes) {
		this.rnStatusDes = rnStatusDes;
	}

	@Column(name="RN_EXPLAIN")
	public String getRnExplain() {
		return rnExplain;
	}

	public void setRnExplain(String rnExplain) {
		this.rnExplain = rnExplain;
	}

	@Column(name="SELF_CHECK_RESULT")
	public String getSelfCheckResult() {
		return selfCheckResult;
	}

	public void setSelfCheckResult(String selfCheckResult) {
		this.selfCheckResult = selfCheckResult;
	}

	@Column(name="REINSPECTION_RESULT")
	public String getReinspectionResult() {
		return reinspectionResult;
	}

	public void setReinspectionResult(String reinspectionResult) {
		this.reinspectionResult = reinspectionResult;
	}

	@Column(name="CU_PLEADER_BACK")
	public String getCuPleaderBack() {
		return ClobUtil.ClobToString(this.cuPleaderBack);
	}

	public void setCuPleaderBack(String cuPleaderBack) throws SerialException, SQLException {
		this.cuPleaderBack = ClobUtil.stringToClob(cuPleaderBack);
	}

	@Column(name="SU_JGJ_BACK")
	public String getSuJgjBack() {
		return ClobUtil.ClobToString(this.suJgjBack);
	}

	public void setSuJgjBack(String suJgjBack) throws SerialException, SQLException {
		this.suJgjBack = ClobUtil.stringToClob(suJgjBack);
	}

	@Temporal(TemporalType.DATE)
	@Column(name="SELF_CHECK_DATE")
	public Date getSelfCheckDate() {
		return selfCheckDate;
	}

	public void setSelfCheckDate(Date selfCheckDate) {
		this.selfCheckDate = selfCheckDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name="REINSPECTION_DATE")
	public Date getReinspectionDate() {
		return reinspectionDate;
	}

	public void setReinspectionDate(Date reinspectionDate) {
		this.reinspectionDate = reinspectionDate;
	}
	@Version
	@Column(name="VERSION")
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="RN_TYPE")
	public String getRectifyNoticeType() {
		return rectifyNoticeType;
	}

	public void setRectifyNoticeType(String rectifyNoticeType) {
		this.rectifyNoticeType = rectifyNoticeType;
	}

	@Column(name="BUS_ORDER_ID")
	public String getBusOrderId() {
		return busOrderId;
	}

	public void setBusOrderId(String busOrderId) {
		this.busOrderId = busOrderId;
	}

	@Column(name="REVIEW")
	public String getReview() {
		return review;
	}

	public void setReview(String review) {
		this.review = review;
	}
}
